### ISSUE TITLE
Eg when using signal.pause(), a KeyboardInterrupt will only be raised on the next controller event

### ISSUE THREAD

**Issue by linusg** [linusg/xbox360controller#1]
Really don't know why, though.

**Comment by yersomegit** [comment]
Yes. This is an irritant isn't it. Being new to python I can't make much sense of it. HOWEVER, and i may be stating the obvious here and you may already be aware.... but....

It seems that the CTRL-C is being caught by the parent thread and (maybe ending it's life - or at least putting it in a state it's ready to exit) however the processing thread lives on since it never gets the interrupt. The processing thread sits there dutifully waiting for the next event, probably in the file read operation (buf=self._dev_file.read(8)) There is sits waiting on the event file to give it more stuff to do. 

The rest is pretty obvious, When an event hits and the file.read completes the thread wakes up and realises the parent is dead and it exits too. (or something like that).

This may not be remotely helpful. But it was fun digging into it anyways.

**Comment by linusg** [comment]
Man, you're a freaking livesaver. Thanks a lot!

This issue is resolved as of https://github.com/linusg/xbox360controller/commit/ac414eb4767d51e0096863d92addaa4f9d037e04.

You were almost right: generally spoken, the behaviour you described can happen and be confusing. In this case, reading from the event file (`self._dev_file.read(8)`) is of course blocking! So even if the main thread exits the event thread still wants to read 8 bytes from the file one last time, which happens when you trigger any event, the next time the loop notices the file was closed and will exit, too.

To resolve this, I stole a small snippet from SO to simply check if anything can be read from the file before attempting the (blocking) method call.

Your comment lead me into the right direction. The "help wanted" label helped! :wink: 

> But it was fun digging into it anyways.

I probably know what you mean. And it makes me more happy than you might think! :grin:

**Comment by yersomegit** [comment]
Ah. Brilliant. what is "SO" 
I've been reading/researching and trying to work out why the event thread would not exit - even when the parent did. I was tring to setup signal handlers and then kill the thread in the signal handler but that didn't work. I understand blocking read but it still had be baffled! The other solution was to change it to a non blocking read and then spin around attempting to read it until successful but checking the exit flag as it went around.  Using select is probably optimal (but i don't know enough python to know).

Glad you got it resolved! Glad i could help!

**Comment by linusg** [comment]
> what is "SO"

Short for "Stack Overflow" :slightly_smiling_face: 

> Using select is probably optimal (but i don't know enough python to know).

Didn't knew about `select` either until now. It also seems to be a Unix system call (which the Python module maps), so nothing Python specific.

**Comment by yersomegit** [comment]
Select or poll are fairly efficient it seems. 
https://pymotw.com/2/select/
