### ISSUE TITLE
A number is printed out when controller object is Initialised 

### ISSUE THREAD

**Issue by yersomegit** [linusg/xbox360controller#4]
A number is printed out on at the start of the program (in my case a '4'). 
I'm pretty sure this is the event file number (ie .../event4)

This possibly comes from  _get_event_file(self) in controller.py
There is a print (event) that i'm not sure of the purpose of

I'm new to python, so it's ways are a bit of a mystery to me - but this doesn't seem right!

Thanks for the really great library

**Comment by linusg** [comment]
Hi @yersomegit,

thanks for opening an issue!

> This possibly comes from _get_event_file(self) in controller.py
> There is a print (event) that i'm not sure of the purpose of

You are 100% right. This was probably there for debugging, is the cause of the issue and should be removed. Thank you very much for pointing it out, I'll remove it and release a new version. I'll notify you then.

> Thanks for the really great library

Glad you like it! I originally made it because all other xbox controller libraries were missing one or another feature, like rumble or LED control. Since I work with Linux only, I was fine using some Linux driver in the background.

Thanks again!

**Comment by linusg** [comment]
Alright, new version is on PyPI!

**Comment by yersomegit** [comment]
Incidentally, Rumble doesn't work for me. i have a wireless xbox360 controller and a USB thing on a Raspberrypi. LED control works (as well as underlying driver lets you.

I suspect my rumble issues are related to xpad rather then your library. 
This is my first time using git and my first time using python - so i'm feeling my way along. Not sure HERE is the right place to have this discussion about rumble but i don't think i should open a bug here since I don't have a well sourced bug report just yet!

**Comment by linusg** [comment]
Oh, no worries. I remember well enough the time when Git and also Python were new to me... And I might have been a little annoying to the maintainer :)

So, feel free to just open another issue, that's no problem most of the time! Obviously, if you spot two bugs most maintainers will appreciate your time and efforts!

I solely own a wired Xbox 360 controller, but I'd be happy to help out - of course the issue can be on both sides. We'll see :)

**Comment by ritiek** [comment]
I have an unofficial Xbox 360 controller. I got my rumbling to work by adding some sleep to the example in README:
```python
from xbox360controller import Xbox360Controller
import time

with Xbox360Controller() as controller:
    controller.set_rumble(0.5, 0.5, 1000)
    time.sleep(0.5)
```
This makes it rumble but for some weird reason the script wouldn't come out of the `with` clause until I move the axis or press a button on the controller.

**Comment by linusg** [comment]
Hi @ritiek!

> I got my rumbling to work by adding some sleep to the example in README:

I'm sorry, maybe the example is misleading? This is intentional as `set_rumble` is non-blocking, so the script needs to "keep running itself" at least as long as the rumble should be.

> This makes it rumble but for some weird reason the script wouldn't come out of the with clause until I move the axis or press a button on the controller.

This is a known bug and stated in the README:

> Please note, there seems to be a bug left that the KeyboardInterrupt will not show up directly when raised, but when the next controller event is registered. In case the program hangs on Ctrl+C, just press or move any of the controller's buttons or axes.

I would be more than happy if someone can help resolving this. Also see [issue #1](https://github.com/linusg/xbox360controller/issues/1).

Cheers!

**Comment by ritiek** [comment]
> I'm sorry, maybe the example is misleading? This is intentional as `set_rumble` is non-blocking, so the script needs to "keep running itself" at least as long as the rumble should be.

I see. I guess it would be helpful to mention this in README.

**Comment by linusg** [comment]
For now I at least [updated `API.md`](https://github.com/linusg/xbox360controller/commit/16a998e1e38909e137f40a71894347428c52f41b#diff-96cc378dcdef180641176501f42183c7L61). I'll make more changes later this day.
